# Open Research

This week we will focus on recommended best practices for transparent and open research.  

**Our goals are to:**

- review the replication crisis and the importance of open research practices

- understand the value of web-based experiments in Psychology

- introduce web technologies for conducting online experiments


[Slides from this week are available here.](https://avenue.cllmcmaster.ca/d2l/le/content/668523/viewContent/5019991/View) NOTE: You need to log in to Avenue to access the slides. 


::: {.callout-important title="Assignments and Exercises"}
**Before next class**

Please work through the [jsPsych 1 assignment (linked here).](assignment_jsPsych_1.qmd)

> NOTE: this assignment will require substantial reading and thought - do not put it off until the last minute! 


Additionally, please continue thinking about a topic in Perception research (broadly defined) that is of interest to you for your individual project. 


Required reading from Experimentology: 

- [Chapter 5: Estimation  ](https://experimentology.io/005-estimation.html)

- [Chapter 6: Inference  ](https://experimentology.io/006-inference.html)

- [Chapter 7: Models  ](https://experimentology.io/007-models.html)



:::




