# Pre-registration

Everything we've discussed so far in the course should have prepared you for this week: Pre-registration. Pre-registration is the act of publishing an experimental design, data collection, and analysis plan, before conducting an experiment. 

After reading week, you will turn in the Pre-registration assignment. This week we prepare you with everything you will need to complete that assignment! You still have a few weeks to refine your experimental design and interests. Be sure you are simultaneously researching your topic of interest and working on this pre-registration between now and the submission deadline. 

**Our goals are to:**

- understand what pre-registration is and when and why to do it

- discuss what goes into a pre-registration

- begin developing a pre-registration for your own experiment 


[Slides from this week are available here.](https://avenue.cllmcmaster.ca/d2l/le/content/668523/viewContent/5040720/View) NOTE: You need to log in to Avenue to access the slides. 

Maya Flannery's guest lecture slides are available here: [https://pnb3ee3-w24.github.io/openScience/open-science.html#/title-slide](https://pnb3ee3-w24.github.io/openScience/open-science.html#/title-slide)


::: {.callout-important title="Assignments and Exercises"}
**Before next class**

Please begin the [pre-registration assignment (linked here).](assignment_preregistration.qmd)

> NOTE: this assignment will require substantial effort - do not put it off until the last minute! 


Come to next class with at least the Background section of the preregistration completed. 


Remember to read Experimentology: 

- [Chapter 11: Preregistration  ](https://experimentology.io/011-prereg.html)

- [Chapter 12: Data Collection  ](https://experimentology.io/012-collection.html)

- [Chapter 13: Project Management  ](https://experimentology.io/013-management.html)

- [Chapter 14: Writing  ](https://experimentology.io/014-writing.html)

- [Chapter 15: Visualization  ](https://experimentology.io/015-viz.html)

:::




