# Open data

This week we will get into the weeds about data. [Danica Evering](https://rdm.mcmaster.ca/about) from [McMaster's Research Data Management Services](https://rdm.mcmaster.ca/) will join us for a lively discussion and in-class exercise using one of McMaster's recently developed data exploration tools. 

**Our goals are to:**

- understand what is meant by open data, as well as potential barriers to publishing open data

- discuss best practices in data management

- explore the wealth of datasets freely available online 


[Slides from this week are available here.](https://avenue.cllmcmaster.ca/d2l/le/content/668523/viewContent/5063552/View)
NOTE: You need to log in to Avenue to access the slides. 

::: {.callout-important title="Assignments and Exercises"}
**Before next class**

Work on [jsPsych Assignment 2](assignment_jsPsych_2.qmd)

> NOTE: this assignment will require substantial reading and thought - do not put it off until the last minute! 


Required reading from Experimentology: 

- [Chapter 8: Measurement  ](https://experimentology.io/008-measurement.html)

- [Chapter 9: Design  ](https://experimentology.io/009-design.html)

- [Chapter 10: Sampling  ](https://experimentology.io/010-sampling.html)

:::




