PNB 3EE3; Fink

# Final Reflection
Your final reflection is a moment to pause and think about all that you have learned throughout the semester and to consider how it might affect your future. 

For each of the bullet points below, please write responses of at least 4 sentences. Feel free to create longer responses. As always, be sure to be clear and concise; these should not be "stream of consciousness" responses. Iterating and editing always make writing stronger.  

## Questions to address

* How has your understanding of *perception* changed from day 1 of class?

* How has your idea of what *research* is changed from day 1 of class?

* What research skills have you most developed during the course? What skills would you most like to develop in the future? 

* What aspects of the pre-registration process did you find most difficult? Why? 
    What apects of the pre-registration process do you find most important? Why? 
    Do you think researchers should be required to pre-register their research? Why or why not? (there is no *right* answer here!)

* How does your experience designing and programming an experiment inform how you understand the research articles you read?

* Are there any aspects of the course you would recommend the instructors change? How can we make the course better for future students? What aspects of the course should stay the same? Why? 


## Assessment
Completing this reflection exercise will earn you 1 bonus percentage point towards your final grade in the course (e.g., if you are at an 89% and complete this reflection, you will be at a 90%).

Please include your responses in your individual GitHub repository in a file named 'reflection_lastName.[ext]' You can include your responses in a markdown file, html doc, pdf - whatever you like! For example, my file might be called 'reflection_Fink.pdf'

**IMPORTANT:** Generative AI (e.g., chatGPT) should not be used to complete this assignment. If we suspect use of generative AI, no bonus will be granted.  