# Resources
Below are resources organized by topic: jsPsych, R, and Experimental Design. If any of you come across a great resource not listed here, please feel free to create a pull request to add it!

## jsPsych
- The online documentation is a great resource. For example, you can check out references like this one: [https://www.jspsych.org/7.3/reference/jspsych-randomization/](https://www.jspsych.org/7.3/reference/jspsych-randomization/) or this one: [https://www.jspsych.org/7.3/plugins/survey-multi-choice/](https://www.jspsych.org/7.3/plugins/survey-multi-choice/) 
- This page links lots of additional tutorials and lectures you can watch: [https://www.jspsych.org/7.3/tutorials/video-tutorials/](https://www.jspsych.org/7.3/tutorials/video-tutorials/)
- You can also check out plugins written by other researchers. For example, here is a paper describing a psychophysics plugin: [https://link.springer.com/article/10.3758/s13428-020-01445-w](https://link.springer.com/article/10.3758/s13428-020-01445-w)
    - And here is the code tutorial to accompany that paper: [https://jspsychophysics.hes.kyushu-u.ac.jp/](https://jspsychophysics.hes.kyushu-u.ac.jp/)
- And here is a paper from the original authors of jsPsych, talking about a new simulation mode they have built: [https://osf.io/preprints/psyarxiv/mq345](https://osf.io/preprints/psyarxiv/mq345)
    - The code: [https://jspsych.github.io/simulation-examples/](https://jspsych.github.io/simulation-examples/) 

## R
- R for Psych: [https://glennwilliams.me/r4psych/](https://glennwilliams.me/r4psych/)
- R graphics cookbook: [https://r-graphics.org/](https://r-graphics.org/ )
- R for data science: [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/ )
- All of the above are books with excellent tutorials that you can work through at your own pace. I highly encourage you to check out these resources, as they will show you how to do everything you could possibly need to do with your data this semester. 

## Experimental Design
In case any of you need/want a little reminder of the basics of experimental design, here is a nice resource [https://opentext.wsu.edu/carriecuttler/chapter/experiment-basics/](https://opentext.wsu.edu/carriecuttler/chapter/experiment-basics/) 

> I encourage you to click “content” in the top left of that link and read through any other sections of the book that you may need a refresher on.

The course textbook, [Experimentology](https://experimentology.io/), is another great resource. 
